### ISSUE TITLE
GHES support?

### ISSUE THREAD

**Issue by retzero** [google-github-actions/auth#136]
### TL;DR

I'm going to configure my GitHub Actions workflow w/ Workload Identity Federation.
Do you support GitHub Enterprise? How can I map our GHES to the issuer?
It would be very nice to get a guide if you have.

### Action YAML

```yaml
None
```

**Comment by sethvargo** [comment]
Hi @retzero 

We rely on GitHub to inject the OIDC token into the environment. We support GitHub Enterprise SaaS, and there's no reason it wouldn't work with GitHub Enterprise Server, provided GitHub adds support for GHES. I found an open issue on the GitHub roadmap at https://github.com/github/roadmap/issues/376. I would suggest reaching out your GitHub TAM or GitHub support to express interest in this feature. Unfortunately we have no control over GHES.

Once support is added, the only major difference would be the token verification endpoint. Instead of https://token.actions.githubusercontent.com, it would be something like https://token.actions.mydomain.com
