### ISSUE TITLE
"Overwriting existing environment variable" warning should be more helpful

### ISSUE THREAD

**Issue by pjh** [google-github-actions/auth#295]
I'm modifying a github workflow that uses google-github-actions/auth. After making some changes to introduce new environment variables I started getting a new warning when my action runs. From the raw logs for my action I determined that this warning is coming from the auth action, presumably from [here](https://github.com/google-github-actions/auth/blob/main/src/main.ts#L212). The warning is:

> "Overwriting existing environment variable GCP_PROJECT (was: "...")"

![image](https://user-images.githubusercontent.com/280787/232618658-fbc685fe-12c2-449c-a07b-b1b7d90193ac.png)

This warning message is incomplete and not actionable, and could be improved. Some thoughts:

* What is the value that the variable is being overwritten with? I can see what it was but not what it will be.
* Who is doing the overwriting? This is really an issue with the GitHub UI (I shouldn't have to dig into the raw logs to figure this out), but until GitHub improves that the message could perhaps say "google-github-actions/auth is overwriting existing..."
* Most importantly, what should I do about it? Does it matter that the auth action is overwriting my environment variable? If it doesn't matter or there's nothing I should do about it, then it would be great to make this a debug statement instead of a warning.

**Comment by sethvargo** [comment]
> What is the value that the variable is being overwritten with? I can see what it was but not what it will be.

We can definitely print the new value if that would be helpful. This warning only prints when the value is different.

> Who is doing the overwriting? This is really an issue with the GitHub UI (I shouldn't have to dig into the raw logs to figure this out), but until GitHub improves that the message could perhaps say "google-github-actions/auth is overwriting existing..."

This is really a function of GitHub's UI, to which they've promised improvements. We do prefix any _errors_ with the name of the GitHub Action.

> Most importantly, what should I do about it? Does it matter that the auth action is overwriting my environment variable? If it doesn't matter or there's nothing I should do about it, then it would be great to make this a debug statement instead of a warning.

GitHub only provides 4 levels of output:

- Debug - [requires user action to enable](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging)
- Info - prints to stdout, along with all command output. Information is easily lost.
- Warning - highlighted in the output and in the job summary
- Error - highlighted in the output and in the job summary with big red font

Based on https://github.com/google-github-actions/auth/pull/156, it became clear that users needed stronger indications that the environment variables were being overwritten.

Errors are actionable, Info/Debug are unactionable. Warnings are _potentially actionable_, which is why they were chosen for this particular message.

**Comment by pjh** [comment]
Thanks for that response. Emitting the new value in the message seems like a good change, and it would help the user determine if the warning is actionable or not.

> This warning only prints when the value is different.

In my case the warning is being printed but it doesn't seem to have any detrimental impact on my workflow's result. I'm wondering if two different projects are actually involved here (the `GCP_PROJECT` I'm setting and the one that the `auth` action is computing), or if perhaps my value is the pretty project name whereas `auth` is using the numeric project ID, causing them to only appear to be different...

**Comment by sethvargo** [comment]
> In my case the warning is being printed but it doesn't seem to have any detrimental impact on my workflow's result. I'm wondering if two different projects are actually involved here (the GCP_PROJECT I'm setting and the one that the auth action is computing), or if perhaps my value is the pretty project name whereas auth is using the numeric project ID, causing them to only appear to be different...

Do you have a link to the workflow?

**Comment by pjh** [comment]
Thanks for the fix!

> Do you have a link to the workflow?

https://github.com/abcxyz/bet-in-a-box/actions/runs/4726073939

**Comment by sethvargo** [comment]
If you upgrade to v1.1.0 (or the latest v1), you'll get the new behavior.
