### ISSUE TITLE
Form of service account email

### ISSUE THREAD

**Issue by geworfener** [google-github-actions/auth#317]
Received the error

`google-github-actions/auth failed with: retry function failed after 1 attempt: service account email *** is not of the form "[name]@[project].iam.gserviceaccount.com. You must manually specify the "project_id" parameter in your GitHub Actions workflow.`

because my service account email has a different form (\*\*\*@\*\*\*.gserviceaccount.com).

1. The code does not quite correspond to the error message, as it does not check the project id.
https://github.com/google-github-actions/auth/blob/ee81b783213cd825ef2dd7da5cd6cfafb9855c74/src/client/workload_identity_client.ts#L73

2. The readme does not explain this requirement.

Can this check be removed or adjusted to also match other possible service account emails?

**Comment by sethvargo** [comment]
What is the domain suffix of the service account?

**Comment by sethvargo** [comment]
This action only supports extracting the project ID from IAM service accounts. The default compute engine service account is of the format `compute-[project number]@developer.gserviceaccount.com`, so it's not possible to get the project ID from that string.

You should explicitly pass in the `project_id` value in the YAML so that the action knows which project to use.

**Comment by geworfener** [comment]
Oh, got it, thanks for the support :)
