### ISSUE TITLE
Clarity intended use of `create_credentials_file: false`

### ISSUE THREAD

**Issue by PeterJCLaw** [google-github-actions/auth#335]
### TL;DR

Explain what the use-case is for `create_credentials_file: false` and/or provide a way to disable the warning about not having checked out a project while still creating a credentials file.

### Detailed design

I have a CI job which purely runs `gcloud` commands. As a result I'm not doing a checkout of my project before using this action. In turn I'm getting the warning which tells me that my workspace is empty.

However in my use-case the workspace is expected to be empty and the warning is a distraction. It would be great if this use-case could be supported.

**Comment by sethvargo** [comment]
Hi @PeterJCLaw - this is documented [in the README](https://github.com/google-github-actions/auth#other-inputs):

> - `create_credentials_file`: (Optional) If true, the action will securely generate a credentials file which can be used for authentication via gcloud and Google Cloud SDKs in other steps in the workflow. The default is true.

The credentials file is exported into `$GITHUB_WORKSPACE`, which makes it available to all future steps and filesystems (including Docker-based GitHub Actions). The file is automatically removed at the end of the job via a post action. In order to use exported credentials, you must add the `actions/checkout` step before calling `auth`. This is due to how GitHub Actions creates `$GITHUB_WORKSPACE`:

There have been a number of issues where users have not used the "actions/checkout" step before our action. Our action relies on the creation of the `$GITHUB_WORKSPACE` directory, which is created by `actions/checkout`. Worse, if a user puts "actions/checkout" _after_ our action, it will delete all contents including the exported credential. 

To verify that a checkout has occurred, we do a small check to see if there are any files in the directory. If there are no files, we emit a _warning_ if there are no files, since there may be legitimate use cases for authenticating without checking out the repository.

The warning is just a warning. If you know what you're doing and it's working as intended, you can ignore this particular warning. If it's really bothersome, you can create a file (`touch $GITHUB_WORKSPACE/.file`) before running the auth action which will trick it into thinking there's a checkout. Alternatively, you can use `google-github-actions/setup-gcloud` directly and manually run `gcloud auth login` with a credentials file or service account key.

**Comment by PeterJCLaw** [comment]
Thanks, yeah, I've put in place a workaround very much like what you describe. I appreciate the warning and the goal it has -- I can well imagine users getting caught out by that behaviour.
I was kinda hoping you might be open to adding an option which squelched the warning without a workaround file?

Separately, the thing I couldn't work out from the docs was what the expected utility of this action was in the case where a credentials file isn't created. Since doing that doesn't affect the rest of the steps in any way it feels like an expensive no-op. Is the goal just to be able to validate some credentials that might later be re-used?

**Comment by sethvargo** [comment]
> Separately, the thing I couldn't work out from the docs was what the expected utility of this action was in the case where a credentials file isn't created. Since doing that doesn't affect the rest of the steps in any way it feels like an expensive no-op. Is the goal just to be able to validate some credentials that might later be re-used?

If you're creating an access token or OIDC token that you use as an output in future steps. For example, if you were building a Docker container and pushing to Artifact Registry, you can skip "create_credentials_file" and pass the access token directly as the password to the docker-login action.
