### ISSUE TITLE
Disable warning ¨Did you forget to use "actions/checkout" before this step?¨

### ISSUE THREAD

**Issue by kopax-polyconseil** [google-github-actions/auth#372]
### TL;DR

Add feature to disable warning ¨Did you forget to use "actions/checkout" before this step?¨

### Detailed design

add inputs `checkout-warning`

When `false`, do not emit warning

### Additional information

<img width="1015" alt="image" src="https://github.com/google-github-actions/auth/assets/77674046/da7e23dd-1b5b-4ed5-a048-5bee8667a461">

It creates a lot of noise =/

**Comment by sethvargo** [comment]
Please provide your action.yml? What are you doing that requires the auth action but not persisted credentials?

**Comment by kopax-polyconseil** [comment]
It is a private repository in charge of doing a dump restore, unfortunately.

It is mainly gcloud commands to create the instance, restore backup, etc... we do not need to checkout anything.

**Comment by kopax-polyconseil** [comment]
I think I now see your point, do you mean I can most likely set `persist_credentials: false` ?


What we do that needs credentials:

- kubectl commands / k8s
- gcloud cli commands
- http gcloud api curl comamnds
- terragrunt commands

**Comment by sethvargo** [comment]
Hi @kopax-polyconseil - then the error message is working as intended. You _need_ to run `actions/checkout` before auth in order to create the shared directory where the credentials will be stored to be accessible by the subsequent steps. 

If you set `persist_credentials` to `false`, then no credentials will be persisted across steps. The filesystem is the only shared "state" across steps in a job.

How are you passing the credentials into those kubectl/gcloud commands?

**Comment by kopax-polyconseil** [comment]
@sethvargo 

<img width="341" alt="image" src="https://github.com/google-github-actions/auth/assets/77674046/6581dd02-b938-4a14-bd66-a3da60493520">


With this step, I do not need to checkout, I just want to disable some cronjobs in k8s. As soon as I add `persist_credentials: false`, I can't use any commands.

However, if I don't add `persist_credentials: false` AND I DO NOT use `@actions/checkout`, then it work. However, I do have those warnings which I want to disable.

It appears to me that the features request have sens as the checkout is unecessary step in my workflow.

Thanks in advance !

**Comment by sethvargo** [comment]
> With this step, I do not need to checkout, I just want to disable some cronjobs in k8s.

You may not need the files, but the `auth` action needs _somewhere_ to store credentials, and it stores them in the checked-out workspace. If that workspace does not exist, there is nowhere for the credential file to be stored. Remember that `auth` is creating a credentials file and exporting the necessary environment variables downstream to find that credential - the credential _has_ to exist somewhere on disk.

> As soon as I add persist_credentials: false, I can't use any commands.

That makes sense - if you do not persist the credential, it will not be available in later steps.

> However, if I don't add persist_credentials: false AND I DO NOT use @actions/checkout, then it work. However, I do have those warnings which I want to disable.

That should *not* work. If it's working, that's not a supported workflow and could break at any time. This is not our doing, but GitHub Actions'. 

> It appears to me that the features request have sens as the checkout is unecessary step in my workflow ?

GitHub Actions has a tendency of introducing and changing behaviors in an undocumented way. I would strongly suggest adding `actions/checkout` as a prior step. You can limit the checkout by setting the clone depth to speed things up. Alternatively, you can manually create `$GITHUB_WORKSPACE`.

> Could you please explain the interest of using this action with persist_credentials: false (use case, ...) ?

The `auth` action can provide credentials as an output (an OAuth 2.0 Access Token or an OIDC token). If you are not using Application Default Credentials (ADC), you can skip the credential export and use the generated token instead. This is an advanced use case, which is why the default option is `true`.
